export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";

export const PURCHASE_SANDWICH_START = "PURCHASE_SANDWICH_START";
export const PURCHASE_SANDWICH_SUCCESS = "PURCHASE_SANDWICH_SUCCESS";
export const PURCHASE_SANDWICH_FAIL = "PURCHASE_SANDWICH_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const RETRIEVE_ORDERLIST_START = "RETRIEVE_ORDERLIST_START";
export const RETRIEVE_ORDERLIST_SUCCESS = "RETRIEVE_ORDERLIST_SUCCESS";
export const RETRIEVE_ORDERLIST_FAIL = "RETRIEVE_ORDERLIST_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
